cursor #e7e0e8
cursor_text_color #cbc4cf

foreground            #e7e0e8
background            #151218
selection_foreground  #342d40
selection_background  #cdc2db
url_color             #d4bbfc

color0   #151218
color1   #ff728d
color2   #7efc99
color3   #ffda72
color4   #c1a5ef
color5   #523d74
color6   #d4bbfc
color7   #f5efff
color8   #9c97a3
color9   #ff9fb1
color10  #a5ffb9
color11  #ffe7a5
color12  #dcc7ff
color13  #e2d0ff
color14  #ece1ff
color15  #fbf8ff
