cursor #e5e1e9
cursor_text_color #c8c5d0

foreground            #e5e1e9
background            #131318
selection_foreground  #302e42
selection_background  #c7c4dc
url_color             #c4c0ff

color0   #131318
color1   #ff7293
color2   #7fff97
color3   #ffd872
color4   #aeaaf2
color5   #434076
color6   #c4c0ff
color7   #f0efff
color8   #9a99a5
color9   #ff9fb5
color10  #a5ffb6
color11  #ffe6a5
color12  #ccc9ff
color13  #d5d2ff
color14  #e4e2ff
color15  #f8f8ff
