# Font Configuration
font_size 12

# Window Configuration
window_padding_width 10
background_opacity 0.6
background_blur 1
hide_window_decorations yes

# Cursor Configuration
cursor_shape block
cursor_blink_interval 1
cursor_trail 1

# Scrollback
scrollback_lines 3000

# Terminal features
copy_on_select yes
strip_trailing_spaces smart
confirm_os_window_close 0 count-background

# Tab configuration
tab_bar_style powerline
tab_bar_align left

# Shell integration
shell_integration enabled

# Dank color generation
include dank-tabs.conf
include dank-theme.conf

map kitty_mod+n new_os_window_with_cwd
map kitty_mod+t new_tab_with_cwd