-- require("")
--
-- local function nmap(lhs, rhs, desc)
--   vim.keymap.set("n", lhs, rhs, { desc = desc })
-- end
--
-- local builtin = require("telescope.builtin")
-- nmap("<leader>sh", builtin.help_tags, "[S]earch [H]elp")
-- nmap("<leader>sk", builtin.keymaps, "[S]earch [K]eymaps")
-- nmap("<leader>sf", builtin.find_files, "[S]earch [F]iles")
-- nmap("<leader>ss", builtin.builtin, "[S]earch [S]elect Telescope")
-- nmap("<leader>sw", builtin.grep_string, "[S]earch current [W]ord")
-- nmap("<leader>sg", builtin.live_grep, "[S]earch by [G]rep")
-- nmap("<leader>sd", builtin.diagnostics, "[S]earch [D]iagnostics")
-- nmap("<leader>sr", builtin.resume, "[S]earch [R]esume")
-- nmap("<leader>s.", builtin.oldfiles, '[S]earch Recent Files ("." for repeat)')
-- nmap("<leader><leader>", builtin.buffers, "[ ] Find existing buffers")
