require("mini.ai").setup({ n_lines = 500 })
require("mini.cursorword").setup()
-- require("mini.diff").setup()
require("mini.git").setup()
require("mini.icons").setup()
require("mini.misc").setup()
require("mini.pairs").setup()
require("mini.sessions").setup()
require("mini.starter").setup()
require("mini.surround").setup()

MiniIcons.mock_nvim_web_devicons()
MiniIcons.tweak_lsp_kind()
MiniMisc.setup_restore_cursor()
MiniMisc.setup_termbg_sync()
